// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetdl0JysfM-icAO3OM3bNEK8xZ7qB-r0',
    appId: '1:596402750525:web:7c1e526ea99cf0a9acd654',
    messagingSenderId: '596402750525',
    projectId: 'prac-8-pcs',
    authDomain: 'prac-8-pcs.firebaseapp.com',
    storageBucket: 'prac-8-pcs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OW05JMRam65OmSe3tx0elMJON_qPx8c',
    appId: '1:596402750525:android:7f3b4f170c97d99cacd654',
    messagingSenderId: '596402750525',
    projectId: 'prac-8-pcs',
    storageBucket: 'prac-8-pcs.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAetdl0JysfM-icAO3OM3bNEK8xZ7qB-r0',
    appId: '1:596402750525:web:7115bdabb021d404acd654',
    messagingSenderId: '596402750525',
    projectId: 'prac-8-pcs',
    authDomain: 'prac-8-pcs.firebaseapp.com',
    storageBucket: 'prac-8-pcs.firebasestorage.app',
  );
}
